### ISSUE TITLE
Updating the section for private link

### ISSUE THREAD

**Issue by pavol-amz** [SAP-samples/btp-build-resilient-apps#144]
I would suggest the section https://github.com/SAP-samples/btp-build-resilient-apps/blob/main/tutorials/05_setupconnectivity/privatelink.md (section Bind application to Private Link service) to be moved or referenced in https://github.com/SAP-samples/btp-build-resilient-apps/blob/main/tutorials/06_deploycapapp/README.md (section 14) or at least put there warning to adjust the MTA deployment descriptor

**Comment by hterminasyan** [comment]
thanks @pavol-amz for the feedback, I made a warning and reference!
