### ISSUE TITLE
Issues when running script "npm run deploy:trial"

### ISSUE THREAD

**Issue by sammok83** [SAP-samples/btp-build-resilient-apps#30]
Hi there,

I'm using the trial instance for this tutorial.

I faced these in **Step 05: Deploy SAP Cloud Application Programming Model (CAP) Application**, point 18

When running npm run deploy:trial, I get the below error.

Creating service "BPVerification-ems" from MTA resource "BPVerification-ems"...
Error monitoring creation or update of services: Error creating service "BPVerification-ems" from offering "enterprise-messaging" and plan "dev": Service broker error: Service broker enterprise-messaging-service-broker failed with: The plan dev, lite and application must not be used anymore. The trial offering for the Event Mesh Service is discontinued. Currently, there is no replacement planned.

Does it mean that this tutorial can't be completed with a trial instance anymore? 

Thanks.

**Comment by maxstreifeneder** [comment]
Hi @sammok83, 

thanks for reporting this issue! Let me please double-check with the Product team how to proceed here. Will come back as soon as I have news! 

Cheers,
Max

**Comment by maxstreifeneder** [comment]
please find the explanation how to proceed here: https://blogs.sap.com/2023/02/01/sap-event-mesh-trial-to-be-retired/ - I'm sorry that this scenario cannot be done anymore in the trial environment.
