### ISSUE TITLE
fatal: Remote branch extension not found in upstream origin

### ISSUE THREAD

**Issue by yack33n** [SAP-samples/btp-build-resilient-apps#79]
When I try to clone from SAP Business Application Studio with command:
git clone -b extension https://github.com/<myUserId>/btp-build-resilient-apps

I get the following error:

Cloning into 'btp-build-resilient-apps'...
fatal: Remote branch extension not found in upstream origin

Are you able to let me know why I am getting this error and how to resolve it?

**Comment by maxstreifeneder** [comment]
Hey there! we have restructured our repo and there are no branches anymore. I've just updated the corresponding tutorial. 

Make sure that you clone your own fork (I can't see any org/user name in the above issue description): 

`git clone https://github.com/yack33n/btp-build-resilient-apps`

**Comment by yack33n** [comment]
Hi Max

Thanx for reply. I have successfully cloned the fork. However now am struggling to deploy the CAP project.

I get the following error:

Service operation failed: Controller operation failed: 404 Updating service "BPVerification-db" failed: Not Found: Error creating service "BPVerification-db" from offering "hana" and plan "hdi-shared": Service plan hdi-shared not found. 

Service operation failed: Controller operation failed: 404 Updating service "BPVerification-ems" failed: Not Found: Error creating service "BPVerification-ems" from offering "enterprise-messaging" and plan "default": Service plan default not found. 
Process failed.

We have only activated the following entitlements:
SAP HANA Cloud - hana-cloud-connection-free & hana-free

I can see we have not activated SAP HANA Schemas & HDI Containers. Are you able to confirm that we are able to proceed with this mission or if a paid plan is required for some of the entitlements?

**Comment by maxstreifeneder** [comment]
Hey! 

I'm sorry for the issues and the late reply (again). You need to entitle hdi-shared as well (which does not have any pricing itself but rather relates to the SAP HANA Cloud instance the HDI stuff is going to be deployed to - which is in your case free, since you have entitled hana-free). 

Unfortunately, there's no free service plan for SAP Event Mesh in Free Tier.
